### PR TITLE
add HTTP request body cli flag

### PR DESCRIPTION
**Pull request by relud**

### CODE REVIEW

**Comment by pajp** [comment]
Looks pretty straightforward to me. Further down the road we'll probably want to refactor the passing of data to the lambda to allow for more flexibility (e.g. custom headers) in the future but this is definitely but this is useful in the meantime.

**Comment by matiaskorhonen** [comment]
@jcxplorer Want to review and merge if it's okay?

**Comment by jcxplorer** [comment]
Looks good to me. Before we release a new version we need to add some kind of a `goad update` command, since at the moment there is no way of updating the lambda function.

**Comment by jcxplorer** [comment]
Thanks @relud for the contribution!

**Pull request merged**
