### PR TITLE
fixing Lambda to be updated on AWS

### PR DESCRIPTION
**Pull request by zeph**
when modified, the lambda function does not get updated on AWS

### CODE REVIEW

**Comment by jcxplorer** [comment]
I'm assuming you want this to test during development (no version change). Is that correct?

What we have at the moment is that the lambda gets updated only after the version is bumped. Maybe we could have a flag to force-update the lambda? That way for actual releases goad would still be fast, as it wouldn't need to reupload the lambda every time it's started (the reason for the way it works currently).

**Comment by zeph** [comment]
@jcxplorer not really, I'm planning to writeOnCopy the embedded zip file that is now in the binary via the bindata.go trick ... with the files of the current directory in which the user is triggering the goad cli

such work folder would be a revision controlled set of INI files that describe real scenarios (as jMeter does)... I'm aiming to completely extend the lambda.go code to implement: 
 - cookie passing through requests
 - templates for the bodyRequest
 - regexp to collect params out of a response to reuse in other requests
and so on...

**Comment by zeph** [comment]
@jcxplorer I'm trying to merge as much as i can, and move on as many pull request as possible... I need some of your help here

my code is always trying to upload itself as it has the assumption that the user has changed stuff

now, as a feature I can change the hardcoded lambda function version from version/version.go to an md5 hash of the Asset() zip file as soon as I have extended it with the user's provided INI files

this way at least we might have a way to compare a hash we have in memory with a hash as a string from the version as reported in the AWS API... and avoid to reupload it

if u have a better idea...

**Comment by jcxplorer** [comment]
Would it be possible to not upload the INI files in the same package as the lambda, but instead use the contents of the INI file(s) as arguments to the lambda function when you invoke it?

How many files are we talking about, and how large do you see them being?

There's a payload limit to invoke a lambda function, so another option would be to have an S3 bucket as part of the infrastructure to upload those INI files to.

I see either option being cleaner and more performant than bundling the INI files with the lambda zip package.

**Comment by zeph** [comment]
@jcxplorer you just move the problem to the upload of the S3 files, I'll still have to do the check

it might be many INI files, over 100, with a complex tree structure, but far below the payload limits given by AWS Lambda API... I might consider using the S3 as storage for huge datasets for loadtesting like usernames listing, that we can have the assumption that it won't change that much

moving the INI to the S3 adds extra complexity that I don't want to have in this phase of development, I might consider it later on if I get dedicated resources to work on it

**Comment by zeph** [comment]
can I invoke the lambda function pushing just that as part of the payload at time of triggering?  (this I dont't know... maybe it is an alternative)

**Comment by jcxplorer** [comment]
You could for example gzip all the INI files, and invoke the lambda with an [additional argument](https://github.com/goadapp/goad/blob/master/lambda/lambda.go#L83) which would be the gzip file encoded as base64.

**Comment by gserra-olx** [comment]
closing, we'll find a better solution with @wmarta-edrans

**Pull request closed without merging**
