### PR TITLE
TTFB swapped with overall request Elapsed Time

### PR DESCRIPTION
**Pull request by zeph**
the overall elapsed time shall be associated to the 4th int64 time measurement as by this structure

```
type RequestResult struct {
	Time             int64  `json:"time"`
	Host             string `json:"host"`
	Type             string `json:"type"`
	Status           int    `json:"status"`
	ElapsedFirstByte int64  `json:"elapsed-first-byte"`
	ElapsedLastByte  int64  `json:"elapsed-last-byte"`
	Elapsed          int64  `json:"elapsed"`
	Bytes            int    `json:"bytes"`
	Timeout          bool   `json:"timeout"`
	ConnectionError  bool   `json:"connection-error"`
	State            string `json:"state"`
}
```

### CODE REVIEW

**Comment by jcxplorer** [comment]
Whoops, I guess we should use named fields to prevent these bugs. Would you like to add those before I merge? 🙂

**Comment by zeph** [comment]
@jcxplorer  I don't know `named fields` yet, these hacks are my learning by writing golang experience ;) ...I'll have a look at it if you think it is the best way to implement them

**Comment by jcxplorer** [comment]
What I meant is that you can use the field names explicitly, like so:

```go
result := RequestResult{
    Time: start.Sub(loadTestStartTime).Nanoseconds(),
    Host: req.URL.Host,
    Type: req.Method,
```

That way the order doesn't matter, which would have prevented this bug 🙂

**Comment by zeph** [comment]
@jcxplorer done, please have a look

**Comment by jcxplorer** [comment]
Brilliant, thanks for this!

**Comment by zeph** [comment]
@jcxplorer you are welcome

**Pull request merged**
